spring.application.name=auth-service

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Veritabanı (Dosya modunda kalsın, verilerin silinmesin)
spring.datasource.url=jdbc:h2:file:./data/nexusauthdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# SQL Başlatma (Sadece tablo yoksa çalıştır dememiz lazım ama şimdilik kalsın)
spring.sql.init.mode=always

# JWT (
nexus.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# 1 Saat (3600000 ms)
nexus.app.jwtExpirationMs=3600000
# 7 Gün (604800000 ms)
nexus.app.jwtRefreshExpirationMs=604800000