spring.application.name=auth-service

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Veritabanı
spring.datasource.url=jdbc:h2:file:./data/nexusauthdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# SQL Başlatma
spring.sql.init.mode=always

# JWT
nexus.app.jwtSecret=BuSeninCokGizliVeGuvenliAnahtarinLutfenKimseylePaylasma123456
nexus.app.jwtExpirationMs=3600000
nexus.app.jwtRefreshExpirationMs=604800000
